kind: ConfigMap
apiVersion: v1
metadata:
  name: identity-cm
  namespace: eshop
  labels:
    app: eshop
    service: identity
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  App__SelfUrl: https://localhost:44351
  ConnectionStrings__IdentityService: Server=localhost,1434;Database=EShopOnAbp_Identity;User Id=sa;password=myPassw0rd
  ConnectionStrings__AdministrationService: Server=localhost,1434;Database=EShopOnAbp_Administration;User Id=sa;password=myPassw0rd
  ConnectionStrings__SaasService: Server=localhost,1434;Database=EShopOnAbp_Saas;User Id=sa;password=myPassw0rd
  Redis__Configuration: localhost:6379
  RabbitMQ__Connections__Default__HostName: localhost

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity
  namespace: eshop
  labels:
    app: eshop
    service: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity
  template:
    metadata:
      labels:
        app: eshop
        service: identity
    spec:
      containers:
        - name: identity-api
          image: eshoponabp/service-identity:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: identity-cm

---

kind: Service
apiVersion: v1
metadata:
  name: identity-api
  namespace: eshop
  labels:
    app: eshop
    service: identity
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    service: identity
